### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by poteto** [MelSumner/ember-metrics#209]
Looking for someone who uses ember-metrics in production to help with maintaining this addon. Pleae let me know if you're interested, thanks!

**Comment by dodeja** [comment]
I can help.

**Comment by dodeja** [comment]
@bgentry just read that thread. I Luke your suggestion. Moving the repo to an org for shared ownership. Happy to help there.

**Comment by bgentry** [comment]
Also to reiterate from the other thread, I registered @emberway explicitly for this purpose (name from Lauren’s blog) and am happy to transfer ownership/control to make this happen 🙂

**Comment by kylenathan** [comment]
Happy to help. We use ember metrics for GTM on a number of production sites.

**Comment by PoslinskiNet** [comment]
Same here, I can help if needed.

**Comment by mazondo** [comment]
Same from us.  We use it across all our sites at Outdoorsy - happy to help!

**Comment by poteto** [comment]
Thanks all. My plan is to split out the adapters (where a large majority of the issues are) into separate repos in the @ember-metrics org–that's where I see maintainers being needed. The ember-metrics addon, in my mind, is just a small service that orchestrates the various adapters users install.

I will add y'all into that org tomorrow.

**Comment by stukalin** [comment]
Hi, @poteto! Could you add me as well?

**Comment by Darshan-Chauhan** [comment]
@poteto , add me as well.

**Comment by GCheung55** [comment]
@poteto I’d be happy to help maintain as well!

**Comment by rstudner** [comment]
I'd be happy to help.  Only using mixpanel but have made some local changes that might be useful to the larger group

**Comment by ballPointPenguin** [comment]
I would like to contribute to this project any way I can.

**Comment by benmurden** [comment]
@poteto I'll help, too, if needed.

**Comment by theklr** [comment]
What's the status on this? I'm seeing a growing list of PRs and currently trying to integrate into my current applications, but the list of issues and PRs and no responses is a concern

**Comment by PoslinskiNet** [comment]
Would be nice to move it to https://github.com/adopted-ember-addons so the community can maintain it if you don't have time for it anymore. What do you think @poteto?

**Comment by poteto** [comment]
@PoslinskiNet Great idea. Do you know someone who can give me permissions to create a public repo in that org?

**Comment by PoslinskiNet** [comment]
@poteto I think @rwjblue can help.

**Comment by PoslinskiNet** [comment]
@poteto Melanie (@MelSumner) told me that all you have to do is just to transfer repo directly to her, and she will take care of the rest. 🤞

**Comment by poteto** [comment]
Done - thanks ember community for stepping up to take this over!
